# -------- Stage 1: Build --------
FROM node:24-alpine AS builder

# Set working directory
WORKDIR /app

# Copy only dependency files first (for caching)
COPY package.json package-lock.json ./

# Install dependencies
RUN npm ci

# Copy rest of the app
COPY . .

# Build the React app
RUN npm run build


# -------- Stage 2: Production --------
FROM nginx:alpine

# Remove default nginx static files
RUN rm -rf /usr/share/nginx/html/*

# Copy build output from builder stage
COPY --from=builder /app/dist /usr/share/nginx/html

# Copy custom nginx config
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Expose port
EXPOSE 80

# Start nginx
CMD ["nginx", "-g", "daemon off;"]



# Instructions to run

# Build image
# docker build -t habitzy-frontend .

# Run container
# docker run -p 3000:80 habitzy-frontend